outputs:
  sort-results: true
linters:
  disable-all: true
  enable:
    # Enabled by default
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # Disabled by default
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goerr113
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomnd
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - importas
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - noctx
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - tagliatelle
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl

    # Don't enable
    # - exhaustivestruct structには任意フィールドもあるので不要
    # - gochecknoglobals グローバル変数で宣言した方がコード量が少なくて済むため
    # - nlreturn         無意味な空行なので不要
    # - depguard         importの依存関係の制限はエラーがややこしいので不要

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  funlen:
    lines: 80
    statements: 40
#　gci:
#    sections:
#      - standard
#      - default
#      - prefix(github.com/jnst/monorepo-go)
#      - blank
#      - dot
#    custom-order: true
